-- Harbor Task 7: child-device enrollment and private security binding.
-- Filename generated by Supabase CLI 2.119.0 in CI run #42.

create table private.device_enrollment_tokens (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  child_id uuid not null references public.children(id) on delete cascade,
  issued_by_user_id uuid not null references auth.users(id) on delete cascade,
  code_digest text not null unique check (char_length(btrim(code_digest)) > 0),
  expires_at timestamptz not null,
  failed_attempts integer not null default 0 check (failed_attempts between 0 and 5),
  consumed_at timestamptz,
  invalidated_at timestamptz,
  created_at timestamptz not null default now(),
  check (expires_at > created_at)
);

create index device_enrollment_tokens_child_active_idx
  on private.device_enrollment_tokens(child_id, created_at desc);

create table private.device_security (
  device_id uuid primary key references public.devices_public(id) on delete cascade,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  public_key_spki text not null check (char_length(btrim(public_key_spki)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

revoke all on table private.device_enrollment_tokens from public, anon, authenticated;
revoke all on table private.device_security from public, anon, authenticated;
grant select, insert, update, delete on table private.device_enrollment_tokens to service_role;
grant select, insert, update, delete on table private.device_security to service_role;

create or replace function private.issue_device_pairing(
  p_parent_user_id uuid,
  p_child_id uuid,
  p_code_digest text,
  p_expires_at timestamptz
)
returns table (
  enrollment_token_id uuid,
  family_id uuid,
  child_id uuid,
  expires_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_family_id uuid;
  v_token_id uuid;
  v_digest text;
begin
  v_digest := btrim(coalesce(p_code_digest, ''));
  if p_parent_user_id is null or p_child_id is null or v_digest = '' then
    raise exception 'pairing input is invalid' using errcode = '22023';
  end if;
  if p_expires_at is null or p_expires_at <= pg_catalog.now() then
    raise exception 'pairing expiry must be in the future' using errcode = '22023';
  end if;

  select c.family_id into v_family_id
  from public.children c
  join public.family_members fm
    on fm.family_id = c.family_id
   and fm.user_id = p_parent_user_id
   and fm.status = 'active'
   and fm.role in ('owner', 'parent')
  where c.id = p_child_id;

  if v_family_id is null then
    raise exception 'child is not authorized for parent' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_child_id::text, 0));

  update private.device_enrollment_tokens as enrollment
  set invalidated_at = pg_catalog.now()
  where enrollment.child_id = p_child_id
    and enrollment.consumed_at is null
    and enrollment.invalidated_at is null;

  insert into private.device_enrollment_tokens (
    family_id, child_id, issued_by_user_id, code_digest, expires_at
  ) values (
    v_family_id, p_child_id, p_parent_user_id, v_digest, p_expires_at
  ) returning id into v_token_id;

  return query select v_token_id, v_family_id, p_child_id, p_expires_at;
end;
$$;

create or replace function private.record_device_claim_failure(p_code_digest text)
returns table (
  failed_attempts integer,
  invalidated boolean
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_failed_attempts integer;
  v_invalidated_at timestamptz;
begin
  update private.device_enrollment_tokens as enrollment
  set failed_attempts = least(enrollment.failed_attempts + 1, 5),
      invalidated_at = case
        when enrollment.failed_attempts + 1 >= 5 then pg_catalog.now()
        else enrollment.invalidated_at
      end
  where enrollment.code_digest = btrim(coalesce(p_code_digest, ''))
    and enrollment.consumed_at is null
    and enrollment.invalidated_at is null
    and enrollment.expires_at > pg_catalog.now()
  returning enrollment.failed_attempts, enrollment.invalidated_at
    into v_failed_attempts, v_invalidated_at;

  if v_failed_attempts is null then
    raise exception 'claim token is unavailable' using errcode = '22023';
  end if;

  return query select v_failed_attempts, v_invalidated_at is not null;
end;
$$;

create or replace function private.claim_device_atomic(
  p_auth_user_id uuid,
  p_code_digest text,
  p_public_key_spki text,
  p_display_name text,
  p_model text,
  p_android_version text,
  p_supervision_mode text
)
returns table (
  device_id uuid,
  family_id uuid,
  child_id uuid
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_token private.device_enrollment_tokens%rowtype;
  v_device_id uuid;
  v_display_name text;
  v_supervision_mode text;
  v_is_anonymous boolean;
begin
  v_display_name := btrim(coalesce(p_display_name, ''));
  v_supervision_mode := btrim(coalesce(p_supervision_mode, ''));

  if p_auth_user_id is null or btrim(coalesce(p_code_digest, '')) = ''
     or btrim(coalesce(p_public_key_spki, '')) = ''
     or char_length(v_display_name) < 1 or char_length(v_display_name) > 100
     or v_supervision_mode not in ('unknown', 'standard', 'full') then
    raise exception 'device claim input is invalid' using errcode = '22023';
  end if;

  select u.is_anonymous into v_is_anonymous
  from auth.users u where u.id = p_auth_user_id;
  if coalesce(v_is_anonymous, false) is not true then
    raise exception 'device identity must be anonymous' using errcode = '42501';
  end if;

  if exists (select 1 from private.device_security ds where ds.auth_user_id = p_auth_user_id) then
    raise exception 'device identity is already bound' using errcode = '23505';
  end if;

  select t.* into v_token
  from private.device_enrollment_tokens t
  where t.code_digest = btrim(p_code_digest)
    and t.consumed_at is null
    and t.invalidated_at is null
    and t.expires_at > pg_catalog.now()
    and t.failed_attempts < 5
  for update;

  if v_token.id is null then
    raise exception 'claim token is unavailable' using errcode = '22023';
  end if;

  insert into public.devices_public (
    family_id, child_id, display_name, model, android_version, supervision_mode, status
  ) values (
    v_token.family_id, v_token.child_id, v_display_name,
    nullif(btrim(coalesce(p_model, '')), ''),
    nullif(btrim(coalesce(p_android_version, '')), ''),
    v_supervision_mode, 'active'
  ) returning id into v_device_id;

  insert into private.device_security (device_id, auth_user_id, public_key_spki)
  values (v_device_id, p_auth_user_id, btrim(p_public_key_spki));

  update private.device_enrollment_tokens as enrollment
  set consumed_at = pg_catalog.now()
  where enrollment.id = v_token.id;

  insert into private.audit_events (
    event_kind, family_id, actor_user_id, resource_type, resource_id, metadata
  ) values (
    'device.enrolled', v_token.family_id, p_auth_user_id, 'device', v_device_id,
    pg_catalog.jsonb_build_object('child_id', v_token.child_id)
  );

  return query select v_device_id, v_token.family_id, v_token.child_id;
end;
$$;

revoke all on function private.issue_device_pairing(uuid, uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function private.record_device_claim_failure(text) from public, anon, authenticated;
revoke all on function private.claim_device_atomic(uuid, text, text, text, text, text, text) from public, anon, authenticated;
grant execute on function private.issue_device_pairing(uuid, uuid, text, timestamptz) to service_role;
grant execute on function private.record_device_claim_failure(text) to service_role;
grant execute on function private.claim_device_atomic(uuid, text, text, text, text, text, text) to service_role;
