-- Harbor Task 9: private desired state, idempotent commands, FCM registration,
-- signed-sync persistence, and immediate device revocation.
-- Filename generated by Supabase CLI 2.119.0 in CI.

alter table public.devices_public
  add column revoked_at timestamptz;

create table private.device_desired_state (
  device_id uuid primary key references private.device_security(device_id) on delete cascade,
  desired_state jsonb not null default '{}'::jsonb,
  desired_state_version bigint not null default 0 check (desired_state_version >= 0),
  acknowledged_version bigint not null default 0 check (acknowledged_version >= 0),
  wake_requested_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  check (acknowledged_version <= desired_state_version)
);

create table private.device_commands (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references private.device_security(device_id) on delete cascade,
  kind text not null check (char_length(btrim(kind)) > 0),
  idempotency_key text not null check (char_length(btrim(idempotency_key)) > 0),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default pg_catalog.now(),
  expires_at timestamptz,
  acknowledged_at timestamptz,
  unique (device_id, idempotency_key)
);

create index device_commands_pending_idx
  on private.device_commands(device_id, created_at)
  where acknowledged_at is null;

create table private.device_fcm_registrations (
  device_id uuid primary key references private.device_security(device_id) on delete cascade,
  token text not null unique check (char_length(btrim(token)) > 0),
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now()
);

revoke all on table private.device_desired_state from public, anon, authenticated;
revoke all on table private.device_commands from public, anon, authenticated;
revoke all on table private.device_fcm_registrations from public, anon, authenticated;
grant select, insert, update, delete on table private.device_desired_state to service_role;
grant select, insert, update, delete on table private.device_commands to service_role;
grant select, insert, update, delete on table private.device_fcm_registrations to service_role;

create or replace function private.harbor_update_device_desired_state(
  p_device_id uuid,
  p_desired_state jsonb,
  p_expected_version bigint
)
returns table (desired_state_version bigint)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_current_version bigint;
  v_next_version bigint;
begin
  if p_device_id is null or p_desired_state is null or p_expected_version is null or p_expected_version < 0 then
    raise exception 'desired state input is invalid' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('desired-state:' || p_device_id::text, 0)
  );

  if not exists (
    select 1
    from public.devices_public d
    join private.device_security ds on ds.device_id = d.id
    where d.id = p_device_id
      and d.status = 'active'
      and d.revoked_at is null
  ) then
    raise exception 'DEVICE_REVOKED' using errcode = '42501';
  end if;

  select s.desired_state_version
    into v_current_version
  from private.device_desired_state s
  where s.device_id = p_device_id;

  v_current_version := coalesce(v_current_version, 0);
  if p_expected_version <> v_current_version then
    raise exception 'STALE_VERSION' using errcode = 'P0001';
  end if;

  v_next_version := v_current_version + 1;

  insert into private.device_desired_state (
    device_id,
    desired_state,
    desired_state_version,
    acknowledged_version,
    wake_requested_at,
    updated_at
  ) values (
    p_device_id,
    p_desired_state,
    v_next_version,
    0,
    pg_catalog.now(),
    pg_catalog.now()
  )
  on conflict (device_id) do update
    set desired_state = excluded.desired_state,
        desired_state_version = excluded.desired_state_version,
        wake_requested_at = excluded.wake_requested_at,
        updated_at = excluded.updated_at;

  return query select v_next_version;
end;
$$;

create or replace function private.harbor_enqueue_device_command(
  p_device_id uuid,
  p_kind text,
  p_idempotency_key text,
  p_payload jsonb,
  p_expires_at timestamptz
)
returns table (
  id uuid,
  kind text,
  idempotency_key text,
  created_at timestamptz,
  expires_at timestamptz,
  payload jsonb
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_kind text := btrim(coalesce(p_kind, ''));
  v_idempotency_key text := btrim(coalesce(p_idempotency_key, ''));
begin
  if p_device_id is null or v_kind = '' or v_idempotency_key = '' or p_payload is null then
    raise exception 'device command input is invalid' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.devices_public d
    where d.id = p_device_id
      and d.status = 'active'
      and d.revoked_at is null
  ) then
    raise exception 'DEVICE_REVOKED' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('device-command:' || p_device_id::text || ':' || v_idempotency_key, 0)
  );

  insert into private.device_commands (device_id, kind, idempotency_key, payload, expires_at)
  values (p_device_id, v_kind, v_idempotency_key, p_payload, p_expires_at)
  on conflict on constraint device_commands_device_id_idempotency_key_key do nothing;

  return query
  select c.id, c.kind, c.idempotency_key, c.created_at, c.expires_at, c.payload
  from private.device_commands c
  where c.device_id = p_device_id
    and c.idempotency_key = v_idempotency_key;
end;
$$;

create or replace function private.harbor_register_device_fcm(
  p_device_id uuid,
  p_token text
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_token text := btrim(coalesce(p_token, ''));
begin
  if p_device_id is null or v_token = '' then
    raise exception 'FCM registration input is invalid' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.devices_public d
    join private.device_security ds on ds.device_id = d.id
    where d.id = p_device_id
      and d.status = 'active'
      and d.revoked_at is null
  ) then
    raise exception 'DEVICE_REVOKED' using errcode = '42501';
  end if;

  insert into private.device_fcm_registrations (device_id, token)
  values (p_device_id, v_token)
  on conflict (device_id) do update
    set token = excluded.token,
        updated_at = pg_catalog.now();

  return true;
end;
$$;

create or replace function private.harbor_sync_device(
  p_device_id uuid,
  p_acknowledged_desired_state_version bigint,
  p_applied_command_ids uuid[]
)
returns table (
  desired_state jsonb,
  desired_state_version bigint,
  commands jsonb
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_desired_state jsonb;
  v_desired_state_version bigint;
  v_acknowledged_version bigint;
  v_commands jsonb;
begin
  if p_device_id is null then
    raise exception 'device sync input is invalid' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.devices_public d
    join private.device_security ds on ds.device_id = d.id
    where d.id = p_device_id
      and d.status = 'active'
      and d.revoked_at is null
  ) then
    raise exception 'DEVICE_REVOKED' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('device-sync:' || p_device_id::text, 0)
  );

  select s.desired_state, s.desired_state_version, s.acknowledged_version
    into v_desired_state, v_desired_state_version, v_acknowledged_version
  from private.device_desired_state s
  where s.device_id = p_device_id;

  v_desired_state := coalesce(v_desired_state, '{}'::jsonb);
  v_desired_state_version := coalesce(v_desired_state_version, 0);
  v_acknowledged_version := coalesce(v_acknowledged_version, 0);

  if p_acknowledged_desired_state_version is not null then
    if p_acknowledged_desired_state_version < 0
       or p_acknowledged_desired_state_version > v_desired_state_version then
      raise exception 'STALE_VERSION' using errcode = 'P0001';
    end if;

    if v_desired_state_version > 0 then
      update private.device_desired_state s
      set acknowledged_version = greatest(s.acknowledged_version, p_acknowledged_desired_state_version),
          updated_at = pg_catalog.now()
      where s.device_id = p_device_id;
    end if;
  end if;

  if p_applied_command_ids is not null and pg_catalog.cardinality(p_applied_command_ids) > 0 then
    update private.device_commands c
    set acknowledged_at = coalesce(c.acknowledged_at, pg_catalog.now())
    where c.device_id = p_device_id
      and c.id = any(p_applied_command_ids);
  end if;

  update public.devices_public d
  set last_seen_at = pg_catalog.now(),
      updated_at = pg_catalog.now()
  where d.id = p_device_id;

  select coalesce(
    pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'id', c.id,
        'kind', c.kind,
        'idempotencyKey', c.idempotency_key,
        'createdAt', c.created_at,
        'expiresAt', c.expires_at,
        'payload', c.payload
      ) order by c.created_at, c.id
    ),
    '[]'::jsonb
  ) into v_commands
  from private.device_commands c
  where c.device_id = p_device_id
    and c.acknowledged_at is null
    and (c.expires_at is null or c.expires_at > pg_catalog.now());

  return query
  select v_desired_state, v_desired_state_version, v_commands;
end;
$$;

create or replace function private.harbor_revoke_device(
  p_device_id uuid,
  p_family_id uuid,
  p_actor_user_id uuid
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_changed boolean := false;
begin
  if p_device_id is null or p_family_id is null or p_actor_user_id is null then
    raise exception 'device revocation input is invalid' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.family_members fm
    where fm.family_id = p_family_id
      and fm.user_id = p_actor_user_id
      and fm.status = 'active'
      and fm.role in ('owner', 'parent')
  ) then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('device-revoke:' || p_device_id::text, 0)
  );

  update public.devices_public d
  set status = 'revoked',
      revoked_at = coalesce(d.revoked_at, pg_catalog.now()),
      updated_at = pg_catalog.now()
  where d.id = p_device_id
    and d.family_id = p_family_id
    and d.status = 'active'
    and d.revoked_at is null;

  v_changed := found;

  if not v_changed and not exists (
    select 1 from public.devices_public d
    where d.id = p_device_id
      and d.family_id = p_family_id
      and d.status = 'revoked'
      and d.revoked_at is not null
  ) then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;

  delete from private.device_fcm_registrations f
  where f.device_id = p_device_id;

  if v_changed then
    insert into private.audit_events (
      event_kind,
      family_id,
      actor_user_id,
      resource_type,
      resource_id,
      metadata
    ) values (
      'device.revoked',
      p_family_id,
      p_actor_user_id,
      'device',
      p_device_id,
      '{}'::jsonb
    );
  end if;

  return true;
end;
$$;

revoke all on function private.harbor_update_device_desired_state(uuid, jsonb, bigint)
  from public, anon, authenticated;
revoke all on function private.harbor_enqueue_device_command(uuid, text, text, jsonb, timestamptz)
  from public, anon, authenticated;
revoke all on function private.harbor_register_device_fcm(uuid, text)
  from public, anon, authenticated;
revoke all on function private.harbor_sync_device(uuid, bigint, uuid[])
  from public, anon, authenticated;
revoke all on function private.harbor_revoke_device(uuid, uuid, uuid)
  from public, anon, authenticated;

grant execute on function private.harbor_update_device_desired_state(uuid, jsonb, bigint)
  to service_role;
grant execute on function private.harbor_enqueue_device_command(uuid, text, text, jsonb, timestamptz)
  to service_role;
grant execute on function private.harbor_register_device_fcm(uuid, text)
  to service_role;
grant execute on function private.harbor_sync_device(uuid, bigint, uuid[])
  to service_role;
grant execute on function private.harbor_revoke_device(uuid, uuid, uuid)
  to service_role;
